### ISSUE TITLE
関数parameterの説明を表示

### ISSUE THREAD

**Issue by ReiHashimoto** [oist/optinist#505]
## 概要
- 各関数のパラメータが何を示すか、GUI上でわかるようにしたい

### Frontend
- サイドバーでパラメータ名をクリックした際に[popover](https://mui.com/material-ui/react-popover/)でdescriptionを表示させる

![Screenshot 2023-05-26 at 13 37 54](https://github.com/oist/optinist/assets/42664619/e37c74d8-234d-4bc1-bf5c-8ede071faf4a)

#### 主な改修対象
- `frontend/src/components/common/ParamFormItemCreator.tsx`
  - `ParamChildItem`がRightDrawerのパラメータキー部分のため、こちらにpopoverを追加
- `frontend/src/utils/param/ParamType.ts`
- `frontend/src/api/params/Params.ts`
- `frontend/src/utils/param/ParamUtils.ts`(`convertToParamMap`)
  - BackendのAPI仕様に対応するようにResponse型などの修正

### Backend
- `/params/{name}`APIでkey, value以外にdescriptionを返す
- parameterのyamlの構造を
    ```
    key1: value1
    key2:
      key2-1: value2-1
      key2-2: value2-2
    ```
    形式から、以下のような形式に変更
    ```
    key1:
      param_description: ...
      value: value1
    key2:
      children:
        key2-1:
          value: value2-1
          param_description: ...
        key2-2:
          value: value2-2
          param_description: ...
    ```
    - nwb.yamlで`description`のキー名が使用されているため、param_descriptionなどの重複しにくいkey名にする必要がある

#### 主な改修対象
- `optinist/config`配下のyamlの構造変更およびパラメータ説明文の記載
  - 以下はv0.4.0時点での数で、v0.5.0の実装の際に追加の可能性あり
  - ファイル数: 22
  - パラメータ数: 340
    - ネストしている場合末端のkey, valueのセットのみカウント
- ParamType, ParamReaderを追加で作成
  - 現状はファイルの読み込みに汎用的なConfigReaderを使用しているが、パラメータとしてのkey, valueとアプリ定義のkey, valueを識別するため型に落とし込む
- `optinist/api/workflow/workflow_params.py`
  - ConfigReader --> ParamReaderに置き換え
  - get_typecheck_paramsからreturnするparamsは従来のkey, valueのみになるようにする
- `optinist/routers/params.py`
  - ConfigReader --> ParamReaderに置き換え
